// Code generated by sdkgen; DO NOT EDIT.

package example

{{ range $val := .Objects }}
// {{ $val.Description }}
type {{ $val.Name }} struct {
    {{ range $field := $val.Fields }} // {{ $field.Description }}
    {{ $field.Name }} {{ extractFieldTypeName $field }}
    {{ end }}
}
{{ end }}